{% set name = "stormevents" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stormevents-{{ version }}.tar.gz
  sha256: 7bf56ffb9b44e19c75024215be9099b36f07b09752eec0774e1e6b331330343a

build:
  noarch: python
  script_env:
    - __version__={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - dunamai
    - pip
    - python >=3.6
    - setuptools >=41.2
  run:
    - beautifulsoup4
    - geopandas
    - netcdf4
    - numpy
    - pandas
    - pyproj >=2.6
    - python >=3.6
    - python-dateutil
    - requests
    - shapely
    - typepigeon >=1.0.5
    - xarray

test:
  imports:
    - stormevents
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oceanmodeling/StormEvents
  summary: Python interfaces for observational data surrounding named storm events
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zacharyburnett
